version: '3'
services:
    kafka:
      image: wurstmeister/kafka
      container_name: my-kafka
      ports:
        - "9092:9092"
      environment:
        - KAFKA_ADVERTISED_HOST_NAME=192.168.178.25
        - KAFKA_ADVERTISED_PORT=9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      depends_on:
        - zookeeper
      volumes:
        - ./data:/opt/data
    zookeeper:
      image: wurstmeister/zookeeper
      container_name: my-zookeeper
      ports:
        - "2181:2181"
      environment:
        - KAFKA_ADVERTISED_HOST_NAME=zookeeper
    elk:
      image: sebp/elk
      container_name: elk
      ports:
        - "5601:5601"
        - "9200:9200"
        - "5044:5044"
    zipkin:
      image: openzipkin/zipkin
      container_name: zipkin
      ports:
        - "9411:9411"
      environment:
#        - STORAGE_TYPE=elasticsearch
#        - ES_HOSTS=http://elk:9200
        - KAFKA_BOOTSTRAP_SERVERS=192.168.178.25:9092
      depends_on:
        - elk